######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 28 23:38:57 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qml
INCLUDEPATH += .
QT += core gui declarative xml

# Input
SOURCES += main.cpp object.cpp
HEADERS += object.h
RESOURCES += resources.qrc
